### PR TITLE
Comply with 0.4 Yazi API changes

### PR DESCRIPTION
**Pull request by saumyajyoti**
See https://github.com/sxyazi/yazi/pull/1966

### CODE REVIEW

**Comment by Rolv-Apneseth** [comment]
Thanks! Would you mind changing this to support both v0.3 and v0.4? E.g. `args = job.args or job`

**Comment by saumyajyoti** [comment]
Sure. I'll update.

**Comment by saumyajyoti** [comment]
Updated

**Comment by Rolv-Apneseth** [comment]
Thanks. Just add a comment explaining why that line exists and it's good to go

**Comment by saumyajyoti** [comment]
> Thanks. Just add a comment explaining why that line exists and it's good to go

Updated.

**Comment by Rolv-Apneseth** [comment]
Great, thank you for the contribution

**Pull request merged**
